language: elixir
elixir:
  - 1.7
otp_release:
  - 20.3
  - 21.0
matrix:
  exclude:
    - otp_release: 20.3
      elixir: 1.7

services:
  - postgresql

addons:
  postgresql: "9.5"

cache:
  directories:
    - _build
    - examples/ecto_poll_queue/_build
    - examples/ecto_poll_queue/deps
    - deps

before_install:
  - wget -q https://binaries.cockroachdb.com/cockroach-v2.0.0.linux-amd64.tgz
  - tar xvf cockroach-v2.0.0.linux-amd64.tgz
  - cd cockroach-v2.0.0.linux-amd64 && nohup ./cockroach start --insecure --host=localhost &

before_script:
  - epmd -daemon
  - MIX_ENV=test mix compile --warnings-as-errors
  - cd examples/ecto_poll_queue && MIX_ENV=cockroach mix do deps.get, compile --warnings-as-errors && cd -
  - cd examples/ecto_poll_queue && MIX_ENV=cockroach mix dialyzer --plt && cd -
  - cd examples/ecto_poll_queue && MIX_ENV=postgres  mix do deps.get, compile --warnings-as-errors && cd -
  - cd examples/ecto_poll_queue && MIX_ENV=postgres  mix dialyzer --plt && cd -
  - MIX_ENV=test mix dialyzer --plt
  - cd cockroach-v2.0.0.linux-amd64 && ./cockroach sql --insecure --host=localhost --execute "create database postgres" && cd -
  - psql -c 'create database honeydew_test;' -U postgres
  # Check for changed files like mix.lock
  - git diff --exit-code

script:
  - elixir --erl "+C multi_time_warp" -S mix test
  - cd examples/ecto_poll_queue && MIX_ENV=cockroach mix do deps.get && cd -
  - cd examples/ecto_poll_queue && MIX_ENV=cockroach mix dialyzer --halt-exit-status && cd -
  - cd examples/ecto_poll_queue && MIX_ENV=postgres mix do deps.get && cd -
  - cd examples/ecto_poll_queue && MIX_ENV=postgres mix dialyzer --halt-exit-status && cd -
  - MIX_ENV=test mix dialyzer --halt-exit-status
